language: python
sudo: false
python: 2.7
services:
    - mysql
env:
    global:
        - DB_HOST=localhost
        - DB_MYSQL_USER=travis
        - DB_PASSWORD=''
        - PYTHONPATH=`pwd`/coda
before_script:
    - mysql -e 'create database coda_local;'
    - cp settings.json.template settings.json
    - python manage.py migrate --settings=coda_project.settings.test
script:
    - py.test --create-db --cov coda --cov-report html

before_install:
    - pip install codecov pytest-cov
after_success:
    - codecov
