db:
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=coda_local
coda: 
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
        - .:/app/
    ports:
        - "8000:80"
    links:
        - db


